# Generated by Django 5.0.4 on 2024-05-01 07:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_ads_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=tinymce.models.HTMLField(default=False, max_length=2500, verbose_name='Контент'),
        ),
    ]
