# Generated by Django 5.0.4 on 2024-05-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_ads_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=models.CharField(default='default content', max_length=2500, verbose_name='Контент'),
        ),
    ]
