# Generated by Django 5.0.4 on 2024-05-01 12:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_ads_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
