# Generated by Django 5.0.4 on 2024-05-01 12:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_ads_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
