# Generated by Django 5.0.4 on 2024-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_ads_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.CharField(default='Текст отклика', max_length=2000, verbose_name='Отклик'),
        ),
    ]
