# Generated by Django 5.0.4 on 2024-05-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='accept_status',
            field=models.BooleanField(default=False, verbose_name='Отклик принят'),
        ),
        migrations.AlterField(
            model_name='response',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.ads', verbose_name='Объявление'),
        ),
    ]
